<pre class='metadata'>
Title: Your Paper Title
Shortname: P1234
Revision: 0
Status: P
Group: WG21
Audience: SG42
URL: https://wg21.link/P1234R0
!Source: <a href="https://github.com/yourgithub/yourrepo/blob/master/yourspec.bs">github.com/yourrepo/blob/master/yourspec.bs</a>
Issue Tracking: GitHub https://github.com/yourgithub/yourrepo/issues
Date: 2018-07-04
Editor: Your Name, Your Company https://example.com/your-company, your-email@example.com, https://example.com/your-personal-website
Editor: Your Coauthor, Your Coauthor's Company https://example.com/your-coauthors-company, your-coauthors-email@example.com, https://example.com/your-coauthors-personal-website
Markup Shorthands: markdown yes
No Abstract: yes
Toggle Diffs: yes
Boilerplate: style-syntax-highlighting off
</pre>

# Introduction # {#intro}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

